class en:
    command__notInGuild = "❌ This command should be run in a server"
    command__notAllowed = "❌ You aren't allowed to run this command"
    command_await_players_result_0 = "🔄 A new game of Werewolf (variant: {0}) will start, {1} use the command `/join` to join"
    command_await_players_result_1 = "❌ Wrong variant: {0}"
    command_await_players_result_2 = "❌ Another game is active"
    command_join_result_0 = "✅ {0} joined the game successfully"
    command_join_result_1 = "❌ The game is not waiting for players or have already started"
    command_join_result_2 = "❌ You have already joined"
    command_join_result_3 = "❌ There are too much players"
    command_see_role_result_0 = "👁️ Your role (original version in French):\n- Name: {0}\n{1}"
    command_see_role_result_1 = "❌ "
    command_start_result_0 = "▶️ The game starts, {0} you can see your rôle with `/see_role`"
    command_start_result_1 = "❌ The game is not ready to start, it could be already running"
    command_start_result_2 = "❌ There are not enough players"
    command_stop_result_0 = "🛑 The game was stopped"
    command_stop_result_1 = "❌ The game is not running"

class fr(en):
    command__notInGuild = "❌ Cette commande devrait être utilisé dans un serveur"
    command_await_players_result_0 = "🔄 Une nouvelle partie de loup-garou (variante : {0}) va commencer, {1} utilisez la commande `/join` pour rejoindre"
    command_await_players_result_1 = "❌ Mauvaise variante: {0}"
    command_await_players_result_2 = "❌ Une autre partie est active"
    command_join_result_0 = "✅ {0} a rejoint la partie"
    command_join_result_1 = "❌ Vous avez déjà rejoint la partie"
    command_join_result_2 = "❌ Une partie est déjà en cours ou aucune partie n'a été démarrée"
    command_join_result_3 = "❌ Il y a trop de joueurs"
    command_start_result_0 = "▶️ Le jeu démarre, {0} vous pourrez voir vos rôles avec `/see_role`"
    command_start_result_1 = "❌ Le jeu n'est pas prêt à démarrer, il pourrait être déjà en cours"
