# Actuellement inutilisé

[EV_NIGHT]
order = ["werewolfes", "whitch"]
werewolfes.kill = nan
whitch.kill = 1
whitch.revive = 1
cupidon.love = 1

[ROLES]
list = ["peasant", "werewolf", "whitch", "cupidon", "hunter"]
ratio = [5, 3, nan, nan, nan, nan]
peasant = {
    team=0
    sname="peasant"
    pname="peasants"
    evnight=[]
}
werewolf = {team=1, sname="werewolf", pname="werewolfes", evnight=["werewolfes"]}
whitch = {team=0, sname="whitch", evnight=["whitch"]}
cupidon = {team=0, sname="cupidon", evnight=["cupidon"]}
hunter